#!/bin/bash

export NODE_PATH=.
browserify --extension=.jsx client.js -o static/bundle.js -v
find styles -name '*.css' | xargs cat > static/bundle.css
uglifyjs -m -c -o static/bundle.min.js -- static/bundle.js
cleancss -o static/bundle.min.css static/bundle.css
mv static/bundle.{min.js,js}
mv static/bundle.{min.css,css}
