#!/bin/bash

export NODE_PATH=.

# Standard pattern to locate test files
PATTERN=${1:-'./**/*_test.js'}
shift

find . -path "$PATTERN" ! -path './node_modules/*' \
  | xargs tap --node-arg=-r --node-arg=babel-core/register "$@"
